compilers:
  - name: clang
    cmake_extra_flags: -DBUILD_PACKAGE:BOOL=ON -DBUILD_TESTING:BOOL=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DBUILD_SWIG:BOOL=ON
    cmake_extra_flags_release: -DBUILD_PACKAGE:BOOL=ON -DBUILD_TESTING:BOOL=ON -DBUILD_SWIG:BOOL=ON -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_OSX_ARCHITECTURES:STRING="x86_64" 
