compilers:
  - name: Visual Studio
    version: 12
    cmake_extra_flags: -DBUILD_PACKAGE:BOOL=ON -DBUILD_TESTING:BOOL=ON -DBUILD_SWIG:BOOL=ON -DBUILD_QT:BOOL=OFF -DBUILD_RUBY:BOOL=ON -DUSE_PCH:BOOL=ON -DBUILD_CSHARP_BINDINGS:BOOL=ON -DMAXIMIZE_CPU_USAGE:BOOL=ON
  - name: Visual Studio
    version: 12
    architecture: Win64
    cmake_extra_flags: -DBUILD_PACKAGE:BOOL=ON -DBUILD_TESTING:BOOL=ON -DBUILD_SWIG:BOOL=ON -DBUILD_QT:BOOL=OFF -DBUILD_RUBY:BOOL=ON -DUSE_PCH:BOOL=ON -DBUILD_CSHARP_BINDINGS:BOOL=ON -DMAXIMIZE_CPU_USAGE:BOOL=ON


